### ISSUE TITLE
How can we disable 3ds secure option?

### ISSUE THREAD

**Issue by abhishek3999** [network-international/sample-merchant-server-javascript#4]
I had tried with 3dSecure skip option true.
Still I can choose options for 3D secure while making payment.
How can we disable so that page will get redirect to success/cancel url?

**Comment by mu1ex** [comment]
Hi @abhishek3999 , skip 3DS is a paid feature which first needs to be first enabled on your merchant account. The flag you are trying to set only works when the feature is enabled on your account. Please contact our support team to know further details on enabling the same.
